language: ruby
sudo: false
cache: bundler
bundler_args: --without tools
script: "bundle exec rake spec"
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.2.7.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://rom-rb.zulipchat.com/api/v1/external/travis?api_key=S1S2GRkXHlzlaCGyUwm7o4lg50IZrwCH&stream=notifications&topic=ci
    on_success: change
    on_failure: always
    on_start: false
