language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without tools
script: "bundle exec rake spec"
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - rbx-3
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
matrix:
  allow_failures:
    - rvm: rbx-3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
